### ISSUE TITLE
Very slow transcription.

### ISSUE THREAD

**Issue by hussain-mustafa990** [krikristoophe/whisper_flutter_plus#9] opened 2023-11-10 18:05 UTC
Hi,
The plugins seems to be working as intended but even when using the WhisperModel.tinyEn the transcription speed is very slow. For a 2 second wav file it's taking upwards of 20 seconds. Isn't whisper.cpp quite fast then why the performance bottleneck here?

Thank you for your help.

**Comment by krikristoophe** [comment] 2023-11-13 09:38
Hello,
From my tests, the transcription is too slow to be usable in real time (in my own app, I display transcription to user only when available. Whisper work as a background task).
Also, the speed is very dependent on 2 things : the device used and the running mode (release is much much faster than debug)

As reminder, this package is only an implementation of whisper.cpp, I'd just managed to make it work but didn't touch to whisper.cpp. I'm not really aware to the whisper functioning. If you find anything to make it work better or faster, feel free to make a PR or proposition !

Have a good day

**Comment by krikristoophe** [comment] 2023-11-13 09:42
Duplicate of https://github.com/krikristoophe/whisper_flutter_plus/issues/10
I keep the other issue because there is details about the demo app that I didn't know and can be useful

**Closed as not planned by krikristoophe** 2023-11-13 09:42 UTC
